# Configuration for CircleCI
# See: https://circleci.com/docs/2.0/configuration-reference

version: 2.1

jobs:
  check_contributor_agreement:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: Check Contributor Agreement
          command: |
            CONTRIBUTOR=${CIRCLE_USERNAME:-CIRCLE_PR_USERNAME}
            grep -r "^${CONTRIBUTOR}" CONTRIBUTORS.md

workflows:
  version: 2
  build:
    jobs:
      - check_contributor_agreement
